# Generated by Django 5.2.1 on 2026-04-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[("due", "Due"), ("paid", "Paid")], max_length=10
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("running_balance", models.FloatField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["date_time", "id"],
            },
        ),
    ]
