# Generated by Django 5.2.1 on 2026-04-20 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["date", "id"]},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date_time",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
